name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: | 
        cd ./hello_world
        cargo build --verbose
    - name: Run tests
      run: | 
        cd ./hello_world 
        cargo test --verbose
    - name: Run grass
      run: | 
        cd ./grass 
        cargo run --verbose
