name: ssh_connent

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
       cd ./ws
       cargo build -p ssh_connect --release --verbose
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{secrets.secret}}
        files: |
          ./ws/ssh_connect/target/release/**
    
    
