name: ssh_connent2

on:
  push:
    branches: [ "master" ]
    tags:
    - '*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with CentOS Docker
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace centos:7 bash -c "
          # 设置 DNS 为 Google DNS（避免 DNS 解析问题）
          echo 'nameserver 8.8.8.8' > /etc/resolv.conf
          # 更新包管理器缓存
          yum clean all
          yum makecache
          # 安装基本依赖和 Rust 工具链
          yum install -y gcc-c++ make curl tar
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          # 加载 Rust 环境
          source $HOME/.cargo/env
          # 安装依赖
          yum install -y rust cargo
          cd ./ws
          cargo build -p ssh_connect --release --verbose
        "
    - name: pacakge
      run: |
        tar -czvf ssh_connent2.tar.gz ./ws/target
    - name: Set tag name based on git describe
      id: tag
      run: echo "TAG_NAME=$(git describe --tags --always)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        token: ${{secrets.secret}}
        files: |
          ssh_connent2.tar.gz
    
    
