name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: | 
        cd ./ws
        cargo build --verbose
    - name: Run tests
      run: | 
        cd ./ws
        cargo test --verbose
    - name: Run web_app
      run: | 
        cd ./ws
        cargo run -p webservice --bin server1  --verbose
