name: ssh_connent

on:
  push:
    branches: [ "master" ]
    tags:
    - '*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with CentOS Docker
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace rust:latest bash -c "
        # 安装 musl 工具链
        apt-get update
        apt-get install -y musl-tools
        # 添加 musl 编译目标
        rustup target add x86_64-unknown-linux-musl
        cd ./ws
        cargo build -p ssh_connect --release --target x86_64-unknown-linux-musl --verbose
        "
    - name: pacakge
      run: |
        tar -czvf ssh_connent.tar.gz ./ws/target
    - name: Set tag name based on git describe
      id: tag
      run: echo "TAG_NAME=$(git describe --tags --always)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        token: ${{secrets.secret}}
        files: |
          ssh_connent.tar.gz
    
    
