name: ssh_connent2

on:
  push:
    branches: [ "master" ]
    tags:
    - '*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with CentOS Docker
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace centos:7 bash -c "
            # 修改 CentOS 镜像源为阿里云镜像
            sed -i 's|http://mirrorlist.centos.org|http://mirrors.aliyun.com/centos|' /etc/yum.repos.d/CentOS-Base.repo
            yum clean all
            yum makecache
            # 安装构建工具
            yum install -y gcc-c++ make curl tar
            # 安装 Rust 工具链
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
            source \$HOME/.cargo/env
            cd ./ws
            cargo build -p ssh_connect --release --verbose
          "
    - name: pacakge
      run: |
        tar -czvf ssh_connent2.tar.gz ./ws/target
    - name: Set tag name based on git describe
      id: tag
      run: echo "TAG_NAME=$(git describe --tags --always)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        token: ${{secrets.secret}}
        files: |
          ssh_connent2.tar.gz
    
    
