name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Build
    #   run: | 
    #     cd ./ws
    #     cargo build --verbose
    # - name: Run tests
    #   run: | 
    #     cd ./ws
    #     cargo test --verbose
    # - name: Run web_app
    #   run: | 
    #     cd ./ws
    #     cargo run -p webservice --bin server1  --verbose
    - name: Run web_rocket
      run: | 
        cd ./ws
        cargo run -p webservice --bin server2  --verbose &
        sleep 10
    - name: Wait for service to be ready 循环等待
      run: |
        until curl -sf http://localhost:8000/hello; do
          echo "Service not ready yet. Waiting..."
          sleep 2
        done
        echo "Service is up and running"
    - name: Test API Endpoint
      run: |
        curl -sf -X GET http://localhost:8000/hello || { echo "hello failed"; exit 1; }
        echo "hello succeeded"
