name: ssh_connent

on:
  push:
    branches: [ "master" ]
    tags:
    - '*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
       cd ./ws
       cargo build -p ssh_connect --release --verbose
    - name: pacakge
      run: |
        tar -czvf ssh_connent.tar.gz ./ws/target
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: laster
        token: ${{secrets.secret}}
        files: |
          ssh_connent.tar.gz
    
    
