name: ssh_connent

on:
  push:
    branches: [ "master" ]
    tags:
    - '*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with CentOS Docker
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace --dns 8.8.8.8 centos:7 bash -c "
          yum install -y gcc-c++ make rust cargo tar
          cd ./ws
          cargo build -p ssh_connect --release --verbose
        "
    - name: pacakge
      run: |
        tar -czvf ssh_connent.tar.gz ./ws/target
    - name: Set tag name based on git describe
      id: tag
      run: echo "TAG_NAME=$(git describe --tags --always)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        token: ${{secrets.secret}}
        files: |
          ssh_connent.tar.gz
    
    
